"""
Excel Q&A Telegram Bot
----------------------
Reads data from an Excel file and lets you ask questions about it in
Telegram. Answers are generated by Google's Gemini API (free tier).

SETUP (see HOSTING_GUIDE.md for details):
1. pip install -r requirements.txt
2. Set environment variables TELEGRAM_BOT_TOKEN and OPENROUTER_API_KEY
   (a .env file works too — see .env.example)
3. Put your Excel file in this folder and update EXCEL_FILE_PATH
4. Run: python bot.py
"""

import os
import time
import logging
import openpyxl
from openai import OpenAI
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters

# ── CONFIG ────────────────────────────────────────────────────────────────
from dotenv import load_dotenv
load_dotenv()  # Loads variables from .env file if it exists

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")
EXCEL_FILE_PATH = os.environ.get("EXCEL_FILE_PATH", "naxcuure(3).xlsx")
OPENROUTER_MODEL = "meta-llama/llama-3.3-70b-instruct:free"

if not TELEGRAM_BOT_TOKEN or not OPENROUTER_API_KEY:
    raise ValueError("Missing TELEGRAM_BOT_TOKEN or OPENROUTER_API_KEY in environment variables.")

# ── LOGGING ───────────────────────────────────────────────────────────────
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

# ── LOAD EXCEL DATA INTO TEXT ────────────────────────────────────────────
def load_excel_as_text(path: str) -> str:
    """Reads every sheet in the workbook and converts it into a plain-text
    table format that's easy for the AI to read and reason over."""
    wb = openpyxl.load_workbook(path, data_only=True)
    parts = []

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            continue

        header = rows[0]
        data_rows = [r for r in rows[1:] if any(cell is not None for cell in r)]

        parts.append(f"=== SHEET: {sheet_name} ({len(data_rows)} rows) ===")
        parts.append(" | ".join(str(c) if c is not None else "" for c in header))

        for row in data_rows:
            parts.append(" | ".join(str(c) if c is not None else "" for c in row))

        parts.append("")  # blank line between sheets

    return "\n".join(parts)


# Load once at startup.
EXCEL_TEXT_DATA = load_excel_as_text(EXCEL_FILE_PATH)
logger.info(f"Loaded Excel data: {len(EXCEL_TEXT_DATA)} characters")

# ── OPENROUTER SETUP ─────────────────────────────────────────────────────────
openrouter_client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=OPENROUTER_API_KEY)

SYSTEM_PROMPT = """You are a helpful assistant that answers questions about a \
spreadsheet of production/manufacturing data. Only use the data provided \
below to answer. If the answer cannot be found in the data, say so clearly \
instead of guessing. Be concise and use plain language. When useful, \
summarize with numbers (totals, counts, averages) rather than dumping raw rows. \
Do not use markdown formatting like asterisks or backticks — reply in plain text.

SPREADSHEET DATA:
{data}
"""

QUOTA_MESSAGE = (
    "Whoa, slow down! You've hit the AI model's free-tier limit "
    "(rate limit or daily quota). If it's a per-minute limit, wait about a "
    "minute and try again. If you've hit the daily cap, it resets at "
    "midnight Pacific time (roughly 12:30-1:30 PM IST)."
)

# ── MEMORY ────────────────────────────────────────────────────────────────
# Simple in-memory per-user conversation history. Lost on restart — that's
# fine for a lightweight Q&A bot, but know that it's not persisted anywhere.
user_histories = {}


def ask_openrouter(question: str, user_id: int) -> str:
    """Single-call design: every question goes straight to the model with
    the full spreadsheet + recent conversation history attached. This costs
    exactly 1 API call per question, which matters a lot on free tiers with
    daily request caps as low as 20-50/day — a 'check first, then answer'
    two-call pattern would silently cut your effective daily questions in
    half, so it's deliberately avoided here."""
    history = user_histories.get(user_id, [])
    history_text = "\n".join([f"User: {q}\nAI: {a}" for q, a in history])

    q_context = f"Previous conversation:\n{history_text}\n\nCURRENT QUESTION: {question}" if history_text else f"QUESTION: {question}"
    prompt = SYSTEM_PROMPT.format(data=EXCEL_TEXT_DATA) + f"\n\n{q_context}\n\nANSWER:"

    # Retry on transient errors (e.g. 503 high demand). Quota/rate-limit
    # errors (429) are NOT retried since retrying won't help within the
    # same minute/day window — we return a clear message immediately instead.
    for attempt in range(3):
        try:
            response = openrouter_client.chat.completions.create(
                model=OPENROUTER_MODEL,
                messages=[{"role": "user", "content": prompt}],
            )
            return response.choices[0].message.content
        except Exception as e:
            error_str = str(e)
            logger.error(f"OpenRouter error (attempt {attempt + 1}): {error_str}")
            if "429" in error_str or "RESOURCE_EXHAUSTED" in error_str:
                return QUOTA_MESSAGE
            if attempt < 2:
                time.sleep(3)
            else:
                return "Sorry, the AI model is currently busy. Please try again in a few seconds."


# ── TELEGRAM HANDLERS ────────────────────────────────────────────────────
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Hi! I can answer questions about your production spreadsheet.\n\n"
        "Just type a question, e.g.:\n"
        "- How many batches were COMPLETED in April?\n"
        "- What's the total variance for BOLNOL TABLET?\n"
        "- Which entries have status RUNNING?\n\n"
        "Commands:\n"
        "/clear - Wipe my short-term memory to start a new topic\n"
        "/reload - Refresh data if the Excel file was updated"
    )


async def clear_memory(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.from_user.id
    user_histories[user_id] = []
    await update.message.reply_text("Memory cleared. Starting fresh.")


async def reload_data(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global EXCEL_TEXT_DATA
    try:
        EXCEL_TEXT_DATA = load_excel_as_text(EXCEL_FILE_PATH)
        await update.message.reply_text(f"Data reloaded ({len(EXCEL_TEXT_DATA)} characters).")
    except Exception as e:
        await update.message.reply_text(f"Failed to reload: {e}")


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.message.from_user.id
    question = update.message.text
    await update.message.chat.send_action("typing")

    answer = ask_openrouter(question, user_id)

    # Save memory (skip storing quota/error messages so they don't pollute context)
    if answer != QUOTA_MESSAGE:
        user_histories.setdefault(user_id, []).append((question, answer))
        if len(user_histories[user_id]) > 4:  # keep last 4 exchanges
            user_histories[user_id].pop(0)

    # Telegram has a strict 4096 character limit per message; split long replies.
    # Plain text only (no parse_mode) since Gemini's output isn't guaranteed
    # to be valid Telegram Markdown and broken formatting causes send failures.
    for i in range(0, len(answer), 4000):
        await update.message.reply_text(answer[i:i + 4000])


# ── MAIN ──────────────────────────────────────────────────────────────────
def main():
    try:
        from keep_alive import keep_alive
        keep_alive()  # Optional background web server for hosts that need a port (e.g. Render Web Service)
    except ImportError:
        logger.info("keep_alive.py not found — skipping (fine if running as a Background Worker or locally).")

    app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("reload", reload_data))
    app.add_handler(CommandHandler("clear", clear_memory))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    logger.info("Bot starting...")
    app.run_polling()


if __name__ == "__main__":
    main()