"""
Excel Q&A Telegram Bot
----------------------
Reads data from an Excel file and lets you ask questions about it in
Telegram. Answers are generated by Google's Gemini API (free tier).

SETUP (see HOSTING_GUIDE.md for details):
1. pip install -r requirements.txt
2. Set environment variables TELEGRAM_BOT_TOKEN and GEMINI_API_KEY
3. Put your Excel file in this folder and update EXCEL_FILE_PATH
4. Run: python bot.py
"""

import os
import logging
import openpyxl
from google import genai
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters

# ── CONFIG ────────────────────────────────────────────────────────────────
from dotenv import load_dotenv
load_dotenv()  # Loads variables from .env file if it exists

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
EXCEL_FILE_PATH = os.environ.get("EXCEL_FILE_PATH", "naxcuure(3).xlsx")
GEMINI_MODEL = "gemini-2.5-flash"  # good free-tier balance of quality + quota

if not TELEGRAM_BOT_TOKEN or not GEMINI_API_KEY:
    raise ValueError("Missing TELEGRAM_BOT_TOKEN or GEMINI_API_KEY in environment variables.")

# ── LOGGING ───────────────────────────────────────────────────────────────
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

# ── LOAD EXCEL DATA INTO TEXT ────────────────────────────────────────────
def load_excel_as_text(path: str) -> str:
    """Reads every sheet in the workbook and converts it into a plain-text
    table format that's easy for the AI to read and reason over."""
    wb = openpyxl.load_workbook(path, data_only=True)
    parts = []

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            continue

        header = rows[0]
        data_rows = [r for r in rows[1:] if any(cell is not None for cell in r)]

        parts.append(f"=== SHEET: {sheet_name} ({len(data_rows)} rows) ===")
        parts.append(" | ".join(str(c) if c is not None else "" for c in header))

        for row in data_rows:
            parts.append(" | ".join(str(c) if c is not None else "" for c in row))

        parts.append("")  # blank line between sheets

    return "\n".join(parts)


# Load once at startup.
EXCEL_TEXT_DATA = load_excel_as_text(EXCEL_FILE_PATH)
logger.info(f"Loaded Excel data: {len(EXCEL_TEXT_DATA)} characters")

# ── GEMINI SETUP ─────────────────────────────────────────────────────────
gemini_client = genai.Client(api_key=GEMINI_API_KEY)

SYSTEM_PROMPT = """You are a helpful assistant that answers questions about a \
spreadsheet of production/manufacturing data. Only use the data provided \
below to answer. If the answer cannot be found in the data, say so clearly \
instead of guessing. Be concise and use plain language. When useful, \
summarize with numbers (totals, counts, averages) rather than dumping raw rows.

SPREADSHEET DATA:
{data}
"""


import time

def ask_gemini(question: str) -> str:
    prompt = SYSTEM_PROMPT.format(data=EXCEL_TEXT_DATA) + f"\n\nQUESTION: {question}\n\nANSWER:"
    
    # Try up to 3 times in case of "503 Service Unavailable" (High Demand)
    for attempt in range(3):
        try:
            response = gemini_client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
            )
            return response.text
        except Exception as e:
            logger.error(f"Gemini error (Attempt {attempt + 1}): {e}")
            if attempt < 2:
                time.sleep(3)  # Wait 3 seconds before retrying
            else:
                return "Sorry, the AI model is currently experiencing high demand and is busy. Please try again in a few seconds!"


# ── TELEGRAM HANDLERS ────────────────────────────────────────────────────
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Hi! I can answer questions about your production spreadsheet.\n\n"
        "Just type a question, e.g.:\n"
        "- How many batches were COMPLETED in April?\n"
        "- What's the total variance for BOLNOL TABLET?\n"
        "- Which entries have status RUNNING?\n\n"
        "Type /reload to refresh data if the Excel file was updated."
    )


async def reload_data(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global EXCEL_TEXT_DATA
    try:
        EXCEL_TEXT_DATA = load_excel_as_text(EXCEL_FILE_PATH)
        await update.message.reply_text(f"Data reloaded ({len(EXCEL_TEXT_DATA)} characters).")
    except Exception as e:
        await update.message.reply_text(f"Failed to reload: {e}")


async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    question = update.message.text
    await update.message.chat.send_action("typing")
    answer = ask_gemini(question)
    await update.message.reply_text(answer)


# ── MAIN ──────────────────────────────────────────────────────────────────
def main():
    from keep_alive import keep_alive
    keep_alive()  # Starts the background web server for Render/UptimeRobot
    
    app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("reload", reload_data))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    logger.info("Bot starting...")
    app.run_polling()


if __name__ == "__main__":
    main()
